# encoding: UTF-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
WhiteCard.create!(:text => "“Tweeting.”")
WhiteCard.create!(:text => "72 virgins.")
WhiteCard.create!(:text => "8 oz. of sweet Mexican black-tar heroin.")
WhiteCard.create!(:text => "A 55-gallon drum of lube.")
WhiteCard.create!(:text => "A bag of magic beans.")
WhiteCard.create!(:text => "A balanced breakfast.")
WhiteCard.create!(:text => "A beached whale.")
WhiteCard.create!(:text => "A big black dick.")
WhiteCard.create!(:text => "A big hoopla about nothing.")
WhiteCard.create!(:text => "A bigger, blacker dick.")
WhiteCard.create!(:text => "A bleached asshole.")
WhiteCard.create!(:text => "A bloody pacifier.")
WhiteCard.create!(:text => "A Bop It.")
WhiteCard.create!(:text => "A brain tumor.")
WhiteCard.create!(:text => "A Burmese tiger pit.")
WhiteCard.create!(:text => "A can of whoop-ass.")
WhiteCard.create!(:text => "A Christmas stocking full of coleslaw.")
WhiteCard.create!(:text => "A clandestine butt scratch.")
WhiteCard.create!(:text => "A cooler full of organs.")
WhiteCard.create!(:text => "A crappy little hand.")
WhiteCard.create!(:text => "A death ray.")
WhiteCard.create!(:text => "A defective condom.")
WhiteCard.create!(:text => "A disappointing birthday party.")
WhiteCard.create!(:text => "A dollop of sour cream.")
WhiteCard.create!(:text => "A drive-by shooting.")
WhiteCard.create!(:text => "A falcon with a cap on its head.")
WhiteCard.create!(:text => "A fetus.")
WhiteCard.create!(:text => "A foul mouth.")
WhiteCard.create!(:text => "A gassy antelope.")
WhiteCard.create!(:text => "A gentle caress of the inner thigh.")
WhiteCard.create!(:text => "A good sniff.")
WhiteCard.create!(:text => "A Gypsy curse.")
WhiteCard.create!(:text => "A homoerotic volleyball montage.")
WhiteCard.create!(:text => "A hot mess.")
WhiteCard.create!(:text => "A Hungry-Man Frozen Christmas Dinner for One.")
WhiteCard.create!(:text => "A lifetime of sadness.")
WhiteCard.create!(:text => "A look-see.")
WhiteCard.create!(:text => "A low standard of living.")
WhiteCard.create!(:text => "A magic hippie love cloud.")
WhiteCard.create!(:text => "A man in yoga pants with a ponytail and feather earrings.")
WhiteCard.create!(:text => "A mating display.")
WhiteCard.create!(:text => "A micropenis.")
WhiteCard.create!(:text => "A middle-aged man on roller skates.")
WhiteCard.create!(:text => "A mime having a stroke.")
WhiteCard.create!(:text => "A monkey smoking a cigar.")
WhiteCard.create!(:text => "A mopey zoo lion.")
WhiteCard.create!(:text => "A murder most foul.")
WhiteCard.create!(:text => "A nuanced critique.")
WhiteCard.create!(:text => "A passionate Latino lover.")
WhiteCard.create!(:text => "A pinata full of scorpions.")
WhiteCard.create!(:text => "A really cool hat.")
WhiteCard.create!(:text => "A rival dojo")
WhiteCard.create!(:text => "A robust mongoloid.")
WhiteCard.create!(:text => "A sad fat dragon with no friends.")
WhiteCard.create!(:text => "A sad handjob.")
WhiteCard.create!(:text => "A salty surprise.")
WhiteCard.create!(:text => "A sassy black woman.")
WhiteCard.create!(:text => "A sausage festival.")
WhiteCard.create!(:text => "A sea of troubles.")
WhiteCard.create!(:text => "A slightly shittier parallel universe.")
WhiteCard.create!(:text => "A snapping turtle biting the tip of your penis.")
WhiteCard.create!(:text => "A soulful rendition of “Ol' Man River.”")
WhiteCard.create!(:text => "A squadron of moles wearing aviator goggles.")
WhiteCard.create!(:text => "A stray pube.")
WhiteCard.create!(:text => "A Super Soaker full of cat pee.")
WhiteCard.create!(:text => "A sweaty, panting leather daddy.")
WhiteCard.create!(:text => "A sweet spaceship.")
WhiteCard.create!(:text => "A thermonuclear detonation.")
WhiteCard.create!(:text => "A tiny horse.")
WhiteCard.create!(:text => "A toxic family environment.")
WhiteCard.create!(:text => "A visually arresting turtleneck.")
WhiteCard.create!(:text => "A web of lies.")
WhiteCard.create!(:text => "A windmill full of corpses.")
WhiteCard.create!(:text => "A woman scorned.")
WhiteCard.create!(:text => "A zesty breakfast burrito.")
WhiteCard.create!(:text => "Aaron Burr.")
WhiteCard.create!(:text => "Active listening.")
WhiteCard.create!(:text => "Actually taking candy from a baby.")
WhiteCard.create!(:text => "Adderall.")
WhiteCard.create!(:text => "African children.")
WhiteCard.create!(:text => "Agriculture.")
WhiteCard.create!(:text => "AIDS.")
WhiteCard.create!(:text => "Alcoholism.")
WhiteCard.create!(:text => "All of this blood.")
WhiteCard.create!(:text => "All-you-can-eat shrimp for $4.99.")
WhiteCard.create!(:text => "Altar boys.")
WhiteCard.create!(:text => "American Gladiators.")
WhiteCard.create!(:text => "Amputees.")
WhiteCard.create!(:text => "An army of skeletons.")
WhiteCard.create!(:text => "An asymmetric boob job.")
WhiteCard.create!(:text => "An erection that lasts more than four hours.")
WhiteCard.create!(:text => "An ether-soaked rag.")
WhiteCard.create!(:text => "An honest cop with nothing left to lose.")
WhiteCard.create!(:text => "An icepick lobotomy.")
WhiteCard.create!(:text => "An M. Night Shyamalan plot twist.")
WhiteCard.create!(:text => "An Oedipus complex.")
WhiteCard.create!(:text => "An unhinged ferris wheel rolling toward the sea.")
WhiteCard.create!(:text => "Anal beads.")
WhiteCard.create!(:text => "Another goddamn vampire movie.")
WhiteCard.create!(:text => "Another shitty year.")
WhiteCard.create!(:text => "Another shop of morphine.")
WhiteCard.create!(:text => "Apologizing.")
WhiteCard.create!(:text => "Appreciative snapping.")
WhiteCard.create!(:text => "Arnold Schwarzenegger.")
WhiteCard.create!(:text => "Asians who aren't good at math.")
WhiteCard.create!(:text => "Assless chaps.")
WhiteCard.create!(:text => "Attitude.")
WhiteCard.create!(:text => "Auschwitz.")
WhiteCard.create!(:text => "Authentic Mexican cuisine.")
WhiteCard.create!(:text => "Autocannibalism.")
WhiteCard.create!(:text => "AXE body spray.")
WhiteCard.create!(:text => "Balls.")
WhiteCard.create!(:text => "Barack Obama.")
WhiteCard.create!(:text => "Basic human decency.")
WhiteCard.create!(:text => "BATMAN!!!")
WhiteCard.create!(:text => "Beating your wives.")
WhiteCard.create!(:text => "Beefin' over turf.")
WhiteCard.create!(:text => "Bees?")
WhiteCard.create!(:text => "Being a bust adult with many important things to do.")
WhiteCard.create!(:text => "Being a dick to children.")
WhiteCard.create!(:text => "Being a dinosaur.")
WhiteCard.create!(:text => "Being a motherfucking sorcerer.")
WhiteCard.create!(:text => "Being awesome at sex.")
WhiteCard.create!(:text => "Being fabulous.")
WhiteCard.create!(:text => "Being marginalized.")
WhiteCard.create!(:text => "Being on fire.")
WhiteCard.create!(:text => "Being rich.")
WhiteCard.create!(:text => "Bill Nye the Science Guy.")
WhiteCard.create!(:text => "Bingeing and purging.")
WhiteCard.create!(:text => "Bitches.")
WhiteCard.create!(:text => "Black people.")
WhiteCard.create!(:text => "Bling.")
WhiteCard.create!(:text => "Booby-trapping the house to foil burglars.")
WhiteCard.create!(:text => "Boogers.")
WhiteCard.create!(:text => "Boris the Soviet Love Hammer.")
WhiteCard.create!(:text => "Bosnian chicken farmers.")
WhiteCard.create!(:text => "Breaking out into song and dance.")
WhiteCard.create!(:text => "Britney Spears at 55.")
WhiteCard.create!(:text => "Bullshit.")
WhiteCard.create!(:text => "Cards Against Humanity.")
WhiteCard.create!(:text => "Carnies.")
WhiteCard.create!(:text => "Catapults.")
WhiteCard.create!(:text => "Catastrophic Urethral Trauma.")
WhiteCard.create!(:text => "Centaurs.")
WhiteCard.create!(:text => "Chainsaws for hands.")
WhiteCard.create!(:text => "Charisma.")
WhiteCard.create!(:text => "Cheating in the Special Olympics.")
WhiteCard.create!(:text => "Child abuse.")
WhiteCard.create!(:text => "Child beauty pageants.")
WhiteCard.create!(:text => "Children on leashes.")
WhiteCard.create!(:text => "Chivalry.")
WhiteCard.create!(:text => "Christopher Walken.")
WhiteCard.create!(:text => "Civilian casualties.")
WhiteCard.create!(:text => "Clams.")
WhiteCard.create!(:text => "Classist Undertones.")
WhiteCard.create!(:text => "Clearing a bloody path through Walmart with a scimitar.")
WhiteCard.create!(:text => "Coat hanger abortions.")
WhiteCard.create!(:text => "Cockfights.")
WhiteCard.create!(:text => "College.")
WhiteCard.create!(:text => "Concealing a boner.")
WhiteCard.create!(:text => "Consultants.")
WhiteCard.create!(:text => "Copping a feel.")
WhiteCard.create!(:text => "Coughing into a vagina.")
WhiteCard.create!(:text => "Count Chocula.")
WhiteCard.create!(:text => "Crippling debt.")
WhiteCard.create!(:text => "Crystal meth.")
WhiteCard.create!(:text => "Cuddling.")
WhiteCard.create!(:text => "Customer service representatives.")
WhiteCard.create!(:text => "Cybernetic enhancements.")
WhiteCard.create!(:text => "Daddy issues.")
WhiteCard.create!(:text => "Daddy's belt.")
WhiteCard.create!(:text => "Dancing with a broom.")
WhiteCard.create!(:text => "Darth Vader.")
WhiteCard.create!(:text => "Date rape.")
WhiteCard.create!(:text => "Dead babies.")
WhiteCard.create!(:text => "Dead parents.")
WhiteCard.create!(:text => "Death by Steven Seagal.")
WhiteCard.create!(:text => "Deflowering the princess.")
WhiteCard.create!(:text => "Dental dams.")
WhiteCard.create!(:text => "Dick Cheney.")
WhiteCard.create!(:text => "Dick fingers.")
WhiteCard.create!(:text => "Dining with cardboard cutouts of the cast of “Friends.”")
WhiteCard.create!(:text => "Doin' it in the butt.")
WhiteCard.create!(:text => "Doing the right thing.")
WhiteCard.create!(:text => "Domino's Oreo Dessert Pizza.")
WhiteCard.create!(:text => "Dorito breath.")
WhiteCard.create!(:text => "Double penetration.")
WhiteCard.create!(:text => "Drinking alone.")
WhiteCard.create!(:text => "Dropping a chandelier on your enemies and riding the rope up.")
WhiteCard.create!(:text => "Dry heaving.")
WhiteCard.create!(:text => "Dwarf tossing.")
WhiteCard.create!(:text => "Dying of dysentery.")
WhiteCard.create!(:text => "Dying.")
WhiteCard.create!(:text => "Eating all of the cookies before the AIDS bake-sale.")
WhiteCard.create!(:text => "Eating an albino.")
WhiteCard.create!(:text => "Eating an entire snowman.")
WhiteCard.create!(:text => "Eating the last known Bison.")
WhiteCard.create!(:text => "Edible underpants.")
WhiteCard.create!(:text => "Elderly Japanese men.")
WhiteCard.create!(:text => "Elf cum.")
WhiteCard.create!(:text => "Embryonic stem cells.")
WhiteCard.create!(:text => "Emotions.")
WhiteCard.create!(:text => "Enormous Scandinavian women.")
WhiteCard.create!(:text => "Erectile dysfunction.")
WhiteCard.create!(:text => "Estrogen.")
WhiteCard.create!(:text => "Ethnic cleansing.")
WhiteCard.create!(:text => "Eugenics.")
WhiteCard.create!(:text => "Euphoria by Calvin Klein.")
WhiteCard.create!(:text => "Exactly what you'd expect.")
WhiteCard.create!(:text => "Exchanging pleasantries.")
WhiteCard.create!(:text => "Existing.")
WhiteCard.create!(:text => "Expecting a burp and vomiting on the floor.")
WhiteCard.create!(:text => "Explosions.")
WhiteCard.create!(:text => "Fabricating statistics.")
WhiteCard.create!(:text => "Famine.")
WhiteCard.create!(:text => "Fancy Feast.")
WhiteCard.create!(:text => "Farting and walking away.")
WhiteCard.create!(:text => "Fear itself.")
WhiteCard.create!(:text => "Feeding Rosie O'Donnell.")
WhiteCard.create!(:text => "Fetal alcohol syndrome.")
WhiteCard.create!(:text => "Fiery poops.")
WhiteCard.create!(:text => "Figgy pudding.")
WhiteCard.create!(:text => "Finding a skeleton.")
WhiteCard.create!(:text => "Finding Waldo.")
WhiteCard.create!(:text => "Finger painting.")
WhiteCard.create!(:text => "Fingering.")
WhiteCard.create!(:text => "Firing a rifle into the air while balls deep in a squealing hog.")
WhiteCard.create!(:text => "Five-Dollar Footlongs.")
WhiteCard.create!(:text => "Flash flooding.")
WhiteCard.create!(:text => "Flesh-eating bacteria.")
WhiteCard.create!(:text => "Flightless birds.")
WhiteCard.create!(:text => "Flying sex snakes.")
WhiteCard.create!(:text => "Foreskin.")
WhiteCard.create!(:text => "Forgetting the Alamo.")
WhiteCard.create!(:text => "Former President George W. Bush.")
WhiteCard.create!(:text => "Free samples.")
WhiteCard.create!(:text => "Friction.")
WhiteCard.create!(:text => "Friendly fire.")
WhiteCard.create!(:text => "Friends who eat all the snacks.")
WhiteCard.create!(:text => "Friends with benefits.")
WhiteCard.create!(:text => "Frolicking.")
WhiteCard.create!(:text => "Fuck Mountain.")
WhiteCard.create!(:text => "Fucking up “Silent Night” in front of 300 parents.")
WhiteCard.create!(:text => "Full frontal nudity.")
WhiteCard.create!(:text => "Gandalf.")
WhiteCard.create!(:text => "Geese.")
WhiteCard.create!(:text => "Genetically engineered super-soldiers.")
WhiteCard.create!(:text => "Genghis Khan.")
WhiteCard.create!(:text => "Genital piercings.")
WhiteCard.create!(:text => "George Clooney's musk.")
WhiteCard.create!(:text => "German dungeon porn.")
WhiteCard.create!(:text => "Getting abducted by Peter Pan.")
WhiteCard.create!(:text => "Getting drunk on mouthwash.")
WhiteCard.create!(:text => "Getting hilariously gang-banged by the Blue Man Group.")
WhiteCard.create!(:text => "Getting in her pants, politely.")
WhiteCard.create!(:text => "Getting naked and watching Nickelodeon.")
WhiteCard.create!(:text => "Getting really high.")
WhiteCard.create!(:text => "Getting so angry that you pop a boner.")
WhiteCard.create!(:text => "Ghandi.")
WhiteCard.create!(:text => "Ghosts.")
WhiteCard.create!(:text => "Gift-wrapping a live hamster.")
WhiteCard.create!(:text => "Giving 110%.")
WhiteCard.create!(:text => "Gladitorial combat.")
WhiteCard.create!(:text => "Glenn Beck being harried by a swarm of buzzards.")
WhiteCard.create!(:text => "Glenn Beck catching his scrotum on a curtain hook.")
WhiteCard.create!(:text => "Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.")
WhiteCard.create!(:text => "Global warming.")
WhiteCard.create!(:text => "Gloryholes.")
WhiteCard.create!(:text => "Goats eating cans.")
WhiteCard.create!(:text => "Goblins.")
WhiteCard.create!(:text => "God.")
WhiteCard.create!(:text => "GoGurt.")
WhiteCard.create!(:text => "Golden showers.")
WhiteCard.create!(:text => "Good grammar.")
WhiteCard.create!(:text => "Grandma.")
WhiteCard.create!(:text => "Grandpa's ashes.")
WhiteCard.create!(:text => "Graphic violence, adult language and some sexual content.")
WhiteCard.create!(:text => "Grave robbing.")
WhiteCard.create!(:text => "Guys who don't call.")
WhiteCard.create!(:text => "Half-assed foreplay.")
WhiteCard.create!(:text => "Harry Potter erotica.")
WhiteCard.create!(:text => "Heartwarming orphans.")
WhiteCard.create!(:text => "Her Royal Highness, Queen Elizabeth II.")
WhiteCard.create!(:text => "Heteronormativity.")
WhiteCard.create!(:text => "Hillary Clinton's death stare.")
WhiteCard.create!(:text => "Hipsters.")
WhiteCard.create!(:text => "Historical revisionism.")
WhiteCard.create!(:text => "Historically black colleges.")
WhiteCard.create!(:text => "Home video of Oprah sobbing into a Lean Cuisine.")
WhiteCard.create!(:text => "Homeless people.")
WhiteCard.create!(:text => "Hope.")
WhiteCard.create!(:text => "Hormone injections.")
WhiteCard.create!(:text => "Horrifying laser hair removal accidents.")
WhiteCard.create!(:text => "Horse meat.")
WhiteCard.create!(:text => "Hot Cheese.")
WhiteCard.create!(:text => "Hot people.")
WhiteCard.create!(:text => "Hot Pockets.")
WhiteCard.create!(:text => "Hulk Hogan.")
WhiteCard.create!(:text => "Hurricane Katrina.")
WhiteCard.create!(:text => "Immaculate conception.")
WhiteCard.create!(:text => "Inappropriate yodeling.")
WhiteCard.create!(:text => "Incest.")
WhiteCard.create!(:text => "Insatiable bloodlust.")
WhiteCard.create!(:text => "Intelligent design.")
WhiteCard.create!(:text => "Intimacy problems.")
WhiteCard.create!(:text => "Italians.")
WhiteCard.create!(:text => "Jafar.")
WhiteCard.create!(:text => "Jean-Claude Van Damme.")
WhiteCard.create!(:text => "Jeff Goldblum.")
WhiteCard.create!(:text => "Jerking off into a pool of children's tears.")
WhiteCard.create!(:text => "Jew-fros.")
WhiteCard.create!(:text => "Jewish fraternities.")
WhiteCard.create!(:text => "Jibber-jabber.")
WhiteCard.create!(:text => "John Wilkes Booth.")
WhiteCard.create!(:text => "Judge Judy.")
WhiteCard.create!(:text => "Just the tip.")
WhiteCard.create!(:text => "Justin Bieber.")
WhiteCard.create!(:text => "Kamikaze pilots.")
WhiteCard.create!(:text => "Kanye West.")
WhiteCard.create!(:text => "Keanu Reaves.")
WhiteCard.create!(:text => "Keg stands.")
WhiteCard.create!(:text => "Kids with ass cancer.")
WhiteCard.create!(:text => "Kim-Jong-il.")
WhiteCard.create!(:text => "Krampus, the Austrian Christmas Monster.")
WhiteCard.create!(:text => "Lactation.")
WhiteCard.create!(:text => "Lady Gaga.")
WhiteCard.create!(:text => "Lance Armstrong's missing testicle.")
WhiteCard.create!(:text => "Land mines.")
WhiteCard.create!(:text => "Laying an egg.")
WhiteCard.create!(:text => "Leaving an awkward voicemail.")
WhiteCard.create!(:text => "Leprosy.")
WhiteCard.create!(:text => "Leveling up.")
WhiteCard.create!(:text => "Licking things to claim them as your own.")
WhiteCard.create!(:text => "Literally eating shit.")
WhiteCard.create!(:text => "Living in a trashcan.")
WhiteCard.create!(:text => "Lockjaw.")
WhiteCard.create!(:text => "Loki, the trickster god.")
WhiteCard.create!(:text => "Loose lips.")
WhiteCard.create!(:text => "Lumberjack fantasies.")
WhiteCard.create!(:text => "Lunchables.")
WhiteCard.create!(:text => "Mad hacky-sack skills.")
WhiteCard.create!(:text => "Making a friend.")
WhiteCard.create!(:text => "Making a pouty face.")
WhiteCard.create!(:text => "Making the penises kiss.")
WhiteCard.create!(:text => "Making the penises kiss.")
WhiteCard.create!(:text => "Mall Santa.")
WhiteCard.create!(:text => "Man meat.")
WhiteCard.create!(:text => "Masturbation.")
WhiteCard.create!(:text => "Me time.")
WhiteCard.create!(:text => "Me.")
WhiteCard.create!(:text => "MechaHitler.")
WhiteCard.create!(:text => "Media coverage.")
WhiteCard.create!(:text => "Medieval Times Dinner & Tournament.")
WhiteCard.create!(:text => "Men.")
WhiteCard.create!(:text => "Menstruation.")
WhiteCard.create!(:text => "Michael Jackson.")
WhiteCard.create!(:text => "Michelle Obama's arms.")
WhiteCard.create!(:text => "Mild autism.")
WhiteCard.create!(:text => "Mooing.")
WhiteCard.create!(:text => "Moral ambiguity.")
WhiteCard.create!(:text => "Morgan Freeman's voice.")
WhiteCard.create!(:text => "Mouth herpes.")
WhiteCard.create!(:text => "Mr. Clean, right behind you.")
WhiteCard.create!(:text => "Muhammad (Praise Be Unto Him).")
WhiteCard.create!(:text => "Multiple stab wounds.")
WhiteCard.create!(:text => "Mutually-assured destruction.")
WhiteCard.create!(:text => "My collection of high-tech sex toys.")
WhiteCard.create!(:text => "My first kill.")
WhiteCard.create!(:text => "My genitals.")
WhiteCard.create!(:text => "My hot cousin.")
WhiteCard.create!(:text => "My humps.")
WhiteCard.create!(:text => "My inner demons.")
WhiteCard.create!(:text => "My machete.")
WhiteCard.create!(:text => "My relationship status.")
WhiteCard.create!(:text => "My sex life.")
WhiteCard.create!(:text => "My soul.")
WhiteCard.create!(:text => "My vagina.")
WhiteCard.create!(:text => "Natalie Portman.")
WhiteCard.create!(:text => "Natural male enhancement.")
WhiteCard.create!(:text => "Natural selection.")
WhiteCard.create!(:text => "Nazis.")
WhiteCard.create!(:text => "Necrophilia.")
WhiteCard.create!(:text => "Neil Patrick Harris.")
WhiteCard.create!(:text => "New Age music.")
WhiteCard.create!(:text => "Nickelback.")
WhiteCard.create!(:text => "Nicolas Cage.")
WhiteCard.create!(:text => "Nipple blades.")
WhiteCard.create!(:text => "Nocturnal emissions.")
WhiteCard.create!(:text => "Not giving a shit about the Third World.")
WhiteCard.create!(:text => "Not reciprocating oral sex.")
WhiteCard.create!(:text => "Nublile slave boys.")
WhiteCard.create!(:text => "Nunchuck moves.")
WhiteCard.create!(:text => "Obesity.")
WhiteCard.create!(:text => "Object permanence.")
WhiteCard.create!(:text => "Old-people smell.")
WhiteCard.create!(:text => "Ominous background music.")
WhiteCard.create!(:text => "One Ring to rule them all.")
WhiteCard.create!(:text => "One thousand Slim Jims.")
WhiteCard.create!(:text => "Oompa-Loompas.")
WhiteCard.create!(:text => "Opposable thumbs.")
WhiteCard.create!(:text => "Overcompensation.")
WhiteCard.create!(:text => "Overpowering your father.")
WhiteCard.create!(:text => "Oversized lollipops.")
WhiteCard.create!(:text => "Pabst Blue Ribbon.")
WhiteCard.create!(:text => "Pac-Man uncontrollably guzzling cum.")
WhiteCard.create!(:text => "Panda sex.")
WhiteCard.create!(:text => "Panty raids.")
WhiteCard.create!(:text => "Parting the Red Sea.")
WhiteCard.create!(:text => "Party poopers.")
WhiteCard.create!(:text => "Passable transvestites.")
WhiteCard.create!(:text => "Passing a kidney stone.")
WhiteCard.create!(:text => "Passive-aggressive Post-it notes.")
WhiteCard.create!(:text => "Pedophiles.")
WhiteCard.create!(:text => "Peeing a little bit.")
WhiteCard.create!(:text => "Penis envy.")
WhiteCard.create!(:text => "Picking up girls at the abortion clinic.")
WhiteCard.create!(:text => "Pictures of boobs.")
WhiteCard.create!(:text => "Pistol-whipping a hostage.")
WhiteCard.create!(:text => "Pixelated bukkake.")
WhiteCard.create!(:text => "Police brutality.")
WhiteCard.create!(:text => "Pooping back and forth. Forever.")
WhiteCard.create!(:text => "Poor life choices.")
WhiteCard.create!(:text => "Poor people.")
WhiteCard.create!(:text => "Poorly-timed Holocaust jokes.")
WhiteCard.create!(:text => "Porn stars.")
WhiteCard.create!(:text => "Powerful thighs.")
WhiteCard.create!(:text => "Prancing.")
WhiteCard.create!(:text => "Praying the gay away.")
WhiteCard.create!(:text => "Preteens.")
WhiteCard.create!(:text => "Pretending to be happy.")
WhiteCard.create!(:text => "Pretending to care.")
WhiteCard.create!(:text => "Pretty Pretty Princess Dress-Up Board Game.")
WhiteCard.create!(:text => "Pterodactyl eggs.")
WhiteCard.create!(:text => "Puberty.")
WhiteCard.create!(:text => "Public ridicule.")
WhiteCard.create!(:text => "Pulling out,")
WhiteCard.create!(:text => "Pumping out a baby every nine months.")
WhiteCard.create!(:text => "Puppies!")
WhiteCard.create!(:text => "Queefing.")
WhiteCard.create!(:text => "Quiche.")
WhiteCard.create!(:text => "Quivering jowls.")
WhiteCard.create!(:text => "Racially-biased SAT questions.")
WhiteCard.create!(:text => "Racism.")
WhiteCard.create!(:text => "Raping and pillaging.")
WhiteCard.create!(:text => "Re-gifting.")
WhiteCard.create!(:text => "Repression.")
WhiteCard.create!(:text => "Republicans.")
WhiteCard.create!(:text => "Revenge fucking.")
WhiteCard.create!(:text => "Riding off into the sunset.")
WhiteCard.create!(:text => "Ripping into a man's chest and pulling out his still-beating heart.")
WhiteCard.create!(:text => "Rising from the grave.")
WhiteCard.create!(:text => "Road head.")
WhiteCard.create!(:text => "Robert Downey, Jr.")
WhiteCard.create!(:text => "RoboCop.")
WhiteCard.create!(:text => "Ronald Reagan.")
WhiteCard.create!(:text => "Roofies.")
WhiteCard.create!(:text => "Ryan Gosling riding in on a white horse.")
WhiteCard.create!(:text => "Same-sex ice dancing.")
WhiteCard.create!(:text => "Santa Claus.")
WhiteCard.create!(:text => "Santa's heavy sack.")
WhiteCard.create!(:text => "Sarah Palin.")
WhiteCard.create!(:text => "Saxophone solos.")
WhiteCard.create!(:text => "Scalping.")
WhiteCard.create!(:text => "Science.")
WhiteCard.create!(:text => "Scientology,")
WhiteCard.create!(:text => "Scrotal frostbite.")
WhiteCard.create!(:text => "Scrotum tickling.")
WhiteCard.create!(:text => "Scrubbing under the folds.")
WhiteCard.create!(:text => "Sean Connery.")
WhiteCard.create!(:text => "Sean Penn.")
WhiteCard.create!(:text => "Seduction.")
WhiteCard.create!(:text => "Self-loathing.")
WhiteCard.create!(:text => "Seppuku.")
WhiteCard.create!(:text => "Serfdom.")
WhiteCard.create!(:text => "Several intertwining love stories featuring Hugh Grant.")
WhiteCard.create!(:text => "Sexting.")
WhiteCard.create!(:text => "Sexual humiliation.")
WhiteCard.create!(:text => "Sexual tension.")
WhiteCard.create!(:text => "Sexy pillow fights.")
WhiteCard.create!(:text => "Sexy siamese twins.")
WhiteCard.create!(:text => "Shaft.")
WhiteCard.create!(:text => "Shapeshifters.")
WhiteCard.create!(:text => "Shaquille O'Neal's acting career.")
WhiteCard.create!(:text => "Sharing needles.")
WhiteCard.create!(:text => "Skeletor.")
WhiteCard.create!(:text => "Slow motion.")
WhiteCard.create!(:text => "Smallpox blankets.")
WhiteCard.create!(:text => "Smegma.")
WhiteCard.create!(:text => "Sniffing glue.")
WhiteCard.create!(:text => "Socks.")
WhiteCard.create!(:text => "Soiling oneself.")
WhiteCard.create!(:text => "Some really fucked-up shit.")
WhiteCard.create!(:text => "Soup that is too hot.")
WhiteCard.create!(:text => "Space Jam on VHS.")
WhiteCard.create!(:text => "Space muffins.")
WhiteCard.create!(:text => "Special musical guest, Cher.")
WhiteCard.create!(:text => "Spectacular abs.")
WhiteCard.create!(:text => "Sperm whales.")
WhiteCard.create!(:text => "Spontaneous human combustion.")
WhiteCard.create!(:text => "Spring break!")
WhiteCard.create!(:text => "Statistically validated stereotypes.")
WhiteCard.create!(:text => "Stephen Hawking talking dirty.")
WhiteCard.create!(:text => "Stifling a giggle at the mention of Hutus and Tutsis.")
WhiteCard.create!(:text => "Stranger danger.")
WhiteCard.create!(:text => "Subduing a grizzly bear and making her your wife.")
WhiteCard.create!(:text => "Sudden Poop Explosion Disease.")
WhiteCard.create!(:text => "Suicidal thoughts.")
WhiteCard.create!(:text => "Sunshine and rainbows.")
WhiteCard.create!(:text => "Surprise sex!")
WhiteCard.create!(:text => "Survivor's guilt.")
WhiteCard.create!(:text => "Sweet, sweet vengeance.")
WhiteCard.create!(:text => "Swiftly achieving orgasm.")
WhiteCard.create!(:text => "Switching to Geico.")
WhiteCard.create!(:text => "Swooping.")
WhiteCard.create!(:text => "Take-backsies.")
WhiteCard.create!(:text => "Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.")
WhiteCard.create!(:text => "Taking down Santa with a surface-to-air missiles.")
WhiteCard.create!(:text => "Taking off your shirt.")
WhiteCard.create!(:text => "Tangled Slinkys.")
WhiteCard.create!(:text => "Tasteful sideboob.")
WhiteCard.create!(:text => "Teaching a robot to love.")
WhiteCard.create!(:text => "Team-building exercises.")
WhiteCard.create!(:text => "Teenage pregnancy.")
WhiteCard.create!(:text => "Tentacle porn.")
WhiteCard.create!(:text => "Testicular torsion.")
WhiteCard.create!(:text => "That thing that electrocutes your abs.")
WhiteCard.create!(:text => "The American Dream.")
WhiteCard.create!(:text => "The Big Bang.")
WhiteCard.create!(:text => "The Blood of Christ.")
WhiteCard.create!(:text => "The boners of the elderly.")
WhiteCard.create!(:text => "The Care Bear Stare.")
WhiteCard.create!(:text => "The Chinese gymnastics team.")
WhiteCard.create!(:text => "The chronic.")
WhiteCard.create!(:text => "The clitoris.")
WhiteCard.create!(:text => "The corporations.")
WhiteCard.create!(:text => "The Dance of the Sugar Plum Fairy.")
WhiteCard.create!(:text => "The day the birds attacked.")
WhiteCard.create!(:text => "The Donald Trump Seal of Approval.")
WhiteCard.create!(:text => "The economy.")
WhiteCard.create!(:text => "The Fanta girls.")
WhiteCard.create!(:text => "The folly of man.")
WhiteCard.create!(:text => "The forbidden fruit.")
WhiteCard.create!(:text => "The Force.")
WhiteCard.create!(:text => "The four arms of Vishnu.")
WhiteCard.create!(:text => "The gays.")
WhiteCard.create!(:text => "The glass ceiling.")
WhiteCard.create!(:text => "The Google.")
WhiteCard.create!(:text => "The grey nutrient broth that sustains Mitt Romney.")
WhiteCard.create!(:text => "The Gulags.")
WhiteCard.create!(:text => "The Hamburglar.")
WhiteCard.create!(:text => "The hardworking Mexican.")
WhiteCard.create!(:text => "The harsh light of day.")
WhiteCard.create!(:text => "The heart of a child.")
WhiteCard.create!(:text => "The hiccups.")
WhiteCard.create!(:text => "The Holy Bible.")
WhiteCard.create!(:text => "The homosexual agenda.")
WhiteCard.create!(:text => "The human body.")
WhiteCard.create!(:text => "The Hustle.")
WhiteCard.create!(:text => "The inevitable heat death of the universe.")
WhiteCard.create!(:text => "The invisible hand.")
WhiteCard.create!(:text => "The Jews.")
WhiteCard.create!(:text => "The KKK.")
WhiteCard.create!(:text => "The Kool-Aid Man.")
WhiteCard.create!(:text => "The Little Engine That Could.")
WhiteCard.create!(:text => "The Make-A-Wish foundation.")
WhiteCard.create!(:text => "The mere concept of Applebee's.")
WhiteCard.create!(:text => "The milk man.")
WhiteCard.create!(:text => "The miracle of childbirth.")
WhiteCard.create!(:text => "The mixing of the races.")
WhiteCard.create!(:text => "The new Radiohead album.")
WhiteCard.create!(:text => "The placenta.")
WhiteCard.create!(:text => "The Pope.")
WhiteCard.create!(:text => "The profoundly handicapped.")
WhiteCard.create!(:text => "The Rapture.")
WhiteCard.create!(:text => "The Rev. Dr. Martin Luther King, Jr.")
WhiteCard.create!(:text => "The shambling corpse of Larry King.")
WhiteCard.create!(:text => "The South.")
WhiteCard.create!(:text => "The Star Wars Holiday Special.")
WhiteCard.create!(:text => "The taint; the grundle; the fleshy fun-bridge.")
WhiteCard.create!(:text => "The Tempur-Pedic Swedish Sleep System.")
WhiteCard.create!(:text => "The terrorists.")
WhiteCard.create!(:text => "The Three-Fifths Compromise.")
WhiteCard.create!(:text => "The tiny calloused hands of the Chinese  children that made this card.")
WhiteCard.create!(:text => "The token minority.")
WhiteCard.create!(:text => "The Trail of Tears.")
WhiteCard.create!(:text => "The true meaning of Christmas.")
WhiteCard.create!(:text => "The Ubermensch.")
WhiteCard.create!(:text => "The underground railroad.")
WhiteCard.create!(:text => "The violation of our most basic human rights.")
WhiteCard.create!(:text => "The Virginia Tech Massacre.")
WhiteCard.create!(:text => "The World of Warcraft.")
WhiteCard.create!(:text => "Third base.")
WhiteCard.create!(:text => "Tiny nipples.")
WhiteCard.create!(:text => "Tom Cruise.")
WhiteCard.create!(:text => "Tongue.")
WhiteCard.create!(:text => "Toni Morrison's vagina.")
WhiteCard.create!(:text => "Too much hair gel.")
WhiteCard.create!(:text => "Tripping balls.")
WhiteCard.create!(:text => "Two midgets shitting into a bucket.")
WhiteCard.create!(:text => "Unfathomable stupidity.")
WhiteCard.create!(:text => "Upgrading homeless people to mobile hotspots.")
WhiteCard.create!(:text => "Uppercuts.")
WhiteCard.create!(:text => "Vehicular manslaughter.")
WhiteCard.create!(:text => "Viagra.")
WhiteCard.create!(:text => "Vigilante justice.")
WhiteCard.create!(:text => "Vigorous jazz hands.")
WhiteCard.create!(:text => "Vikings.")
WhiteCard.create!(:text => "Waiting 'til marriage.")
WhiteCard.create!(:text => "Waking up half-naked in a Denny's parking lot.")
WhiteCard.create!(:text => "Waterboarding.")
WhiteCard.create!(:text => "Weapons-grade plutonium.")
WhiteCard.create!(:text => "Wearing an octopus for a hat.")
WhiteCard.create!(:text => "Wearing underwear inside-out to avoid doing laundry.")
WhiteCard.create!(:text => "Whatever Kwanzaa is supposed to be about.")
WhiteCard.create!(:text => "When you fart and a little bit comes out.")
WhiteCard.create!(:text => "Whining like a little bitch.")
WhiteCard.create!(:text => "Whipping a disobedient slave.")
WhiteCard.create!(:text => "Whipping it out.")
WhiteCard.create!(:text => "White people.")
WhiteCard.create!(:text => "White privilege.")
WhiteCard.create!(:text => "Wifely duties.")
WhiteCard.create!(:text => "William Shatner.")
WhiteCard.create!(:text => "Winking at old people.")
WhiteCard.create!(:text => "Wiping her butt.")
WhiteCard.create!(:text => "Women in yogurt commercials.")
WhiteCard.create!(:text => "Women's suffrage.")
WhiteCard.create!(:text => "Words, words, words.")
WhiteCard.create!(:text => "World peace.")
WhiteCard.create!(:text => "Yeast.")
WhiteCard.create!(:text => "YOU MUST CONSTRUCT ADDITIONAL PYLONS.")
WhiteCard.create!(:text => "Zeus's sexual appetites.")

BlackCard.create!(:text => "________, kid-tested mother-approved.", :blanks => 1)
BlackCard.create!(:text => "________: good to the last drop.", :blanks => 1)
BlackCard.create!(:text => "________? There's an app for that.", :blanks => 1)
BlackCard.create!(:text => "________. Betcha can't have just one.", :blanks => 1)
BlackCard.create!(:text => "________. High five bro.", :blanks => 1)
BlackCard.create!(:text => "________. It's a trap!", :blanks => 1)
BlackCard.create!(:text => "________. That's how I want to die.", :blanks => 1)
BlackCard.create!(:text => "________ + ________ = ________", :blanks => 3)
BlackCard.create!(:text => "I went from ________ to ________, all thanks to ________.", :blanks => 3)
BlackCard.create!(:text => "Make a haiku. ________ ________ ________", :blanks => 3)
BlackCard.create!(:text => "________ would be woefully incomplete without ________.", :blanks => 2)
BlackCard.create!(:text => "________ is a slippery slope that leads to ________.", :blanks => 2)
BlackCard.create!(:text => "An international tribunal has found ________ guilty of ________.", :blanks => 2)
BlackCard.create!(:text => "And the Academy Award for ________ goes to ________.", :blanks => 2)
BlackCard.create!(:text => "Before ________, all we had was ________.", :blanks => 2)
BlackCard.create!(:text => "Dear Sir or Madam, We regret to inform you that the office of ________ has denied your request for ________.", :blanks => 2)
BlackCard.create!(:text => "For my next trick, I will pull ________ out of ________.", :blanks => 2)
BlackCard.create!(:text => "I never truly understood ________ until I encountered ________.", :blanks => 2)
BlackCard.create!(:text => "I spent my whole life working toward ________, only to have it ruined by ________.", :blanks => 2)
BlackCard.create!(:text => "If God didn't want us to enjoy ________, he wouldn't have given us ________.", :blanks => 2)
BlackCard.create!(:text => "In a pinch, ________ can be a suitable substitute for ________.", :blanks => 2)
BlackCard.create!(:text => "In a world ravaged by ________, our only solace is ________.", :blanks => 2)
BlackCard.create!(:text => "In M. Night Shamalan's new movie, Bruce Willis discovers that ________ had really been ________ all along.", :blanks => 2)
BlackCard.create!(:text => "Lifetime presents ________, the story of ________.", :blanks => 2)
BlackCard.create!(:text => "Michael Bay's new three-hour action epic pits ________ against ________.", :blanks => 2)
BlackCard.create!(:text => "Rumor has it that Vladimir Putin's favorite dish is ________ stuffed with ________.", :blanks => 2)
BlackCard.create!(:text => "Step 1: ________ Step 2 ________ Step 3: Profit.", :blanks => 2)
BlackCard.create!(:text => "That's right I killed ________. How you ask? ________.", :blanks => 2)
BlackCard.create!(:text => "What's the next superhero/sidekick duo? ________ and ________", :blanks => 2)
BlackCard.create!(:text => "When I was tripping on acid ________ turned into ________.", :blanks => 2)
BlackCard.create!(:text => "You haven't truly lived until you've experienced ________ and ________ at the same time.", :blanks => 2)
BlackCard.create!(:text => "A romantic candlelit dinner would be incomplete without ________.", :blanks => 1)
BlackCard.create!(:text => "After blacking out during New Year's Eve, I was awoken by ________.", :blanks => 1)
BlackCard.create!(:text => "After months of debate, the Occupy Wall Street General Assembly could only agree on “More ________!”", :blanks => 1)
BlackCard.create!(:text => "After the earthquake, Sean Penn bought ________ to the people of Haiti.", :blanks => 1)
BlackCard.create!(:text => "Alternative medicine is now embracing the curative powers of ________.", :blanks => 1)
BlackCard.create!(:text => "And I would have gotten away with it, too, if it hadn't been for ________.", :blanks => 1)
BlackCard.create!(:text => "Anthropologists have recently discovered a primitive tribe that worships ________.", :blanks => 1)
BlackCard.create!(:text => "Before I run for president, I must destroy all evidence of my involvement with ________.", :blanks => 1)
BlackCard.create!(:text => "BILLY MAYS HERE FOR ________.", :blanks => 1)
BlackCard.create!(:text => "But before I kill you, Mr. Bond, I must show you ________.", :blanks => 1)
BlackCard.create!(:text => "Charades was ruined for me forever when my mom had to act out ________.", :blanks => 1)
BlackCard.create!(:text => "Coming to Broadway this season, ________: The Musical.", :blanks => 1)
BlackCard.create!(:text => "Dear Abby, I'm having some trouble with ________ and would like your advice.", :blanks => 1)
BlackCard.create!(:text => "During his midlife crisis, my dad got really into ________.", :blanks => 1)
BlackCard.create!(:text => "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of ________.", :blanks => 1)
BlackCard.create!(:text => "During sex, I like to think about ________.", :blanks => 1)
BlackCard.create!(:text => "Every Christmas my uncle gets drunk and tells the story about ________.", :blanks => 1)
BlackCard.create!(:text => "Everyone down on the ground! We don't want to hurt anyone. We're just here for ________.", :blanks => 1)
BlackCard.create!(:text => "He who controls ________ controls the world.", :blanks => 1)
BlackCard.create!(:text => "How am I maintaining my relationship status? ________", :blanks => 1)
BlackCard.create!(:text => "I do not know with what weapons World War III will be fought, but World War IV will be fought with ________.", :blanks => 1)
BlackCard.create!(:text => "I drink to forget ________.", :blanks => 1)
BlackCard.create!(:text => "I got 99 problems but ________ ain't one.", :blanks => 1)
BlackCard.create!(:text => "I learned the hard way that you can't cheer up a grieving friend with ________.", :blanks => 1)
BlackCard.create!(:text => "I'm sorry professor, but I couldn't complete my homework because of ________.", :blanks => 1)
BlackCard.create!(:text => "In 1,000 years when paper money is but a distant memory, ________ will be our currency.", :blanks => 1)
BlackCard.create!(:text => "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on ________.", :blanks => 1)
BlackCard.create!(:text => "In his new self-produced album, Kanye West raps over the sounds of ________.", :blanks => 1)
BlackCard.create!(:text => "In his newest and most difficult stunt, David Blaine must escape from ________.", :blanks => 1)
BlackCard.create!(:text => "In its new tourism campaign, Detroit proclaims that it has finally eliminated ________.", :blanks => 1)
BlackCard.create!(:text => "In L.A. county Jail, word is you can trade 200 cigarettes for ________.", :blanks => 1)
BlackCard.create!(:text => "In Michael Jackson's final moments, he thought about ________.", :blanks => 1)
BlackCard.create!(:text => "In Rome, there are whisperings that the Vatican has a secret room devoted to ________.", :blanks => 1)
BlackCard.create!(:text => "In the distant future, historians will agree that ________ marked the beginning of America's decline.", :blanks => 1)
BlackCard.create!(:text => "In the new Disney Channel Original Movie, Hannah Montana struggles with ________ for the first time.", :blanks => 1)
BlackCard.create!(:text => "Instead of coal, Santa now gives the bad children ________ .", :blanks => 1)
BlackCard.create!(:text => "It's a pity that kids these days are all getting involved with ________.", :blanks => 1)
BlackCard.create!(:text => "Jesus is ________.", :blanks => 1)
BlackCard.create!(:text => "Life for American Indians was forever changed when the White Man introduced them to ________.", :blanks => 1)
BlackCard.create!(:text => "Little Miss Muffet, Sat on a tuffet, Eating her curds and ________.", :blanks => 1)
BlackCard.create!(:text => "Major League Baseball has banned ________ for giving players an unfair advantage.", :blanks => 1)
BlackCard.create!(:text => "Maybe she's born with it. Maybe it's ________.", :blanks => 1)
BlackCard.create!(:text => "Members of New York's social elite are paying thousands of dollars just to experience ________.", :blanks => 1)
BlackCard.create!(:text => "MTV's new reality show features eight washed-up celebrities living with ________.", :blanks => 1)
BlackCard.create!(:text => "My country, 'tis of thee, sweet land of ________.", :blanks => 1)
BlackCard.create!(:text => "My mom freaked out when she looked at my browser history and found ________.com/________.", :blanks => 2)
BlackCard.create!(:text => "My new favorite porn star is Joey “________” McGee.", :blanks => 1)
BlackCard.create!(:text => "Next from J.K. Rowling: Harry Potter and the Chamber of ________.", :blanks => 1)
BlackCard.create!(:text => "Next on ESPN2: The World Series of ________.", :blanks => 1)
BlackCard.create!(:text => "Next time on Dr. Phil: How to talk to your child about ________.", :blanks => 1)
BlackCard.create!(:text => "On the third day of Christmas, my true love game to me: three French hens, two turtle doves, and ________.", :blanks => 1)
BlackCard.create!(:text => "Only two things in life are certain: death and ________.", :blanks => 1)
BlackCard.create!(:text => "Science will never explain the origin of ________.", :blanks => 1)
BlackCard.create!(:text => "Studies show that lab rats navigate mazes 50% faster after being exposed to ________", :blanks => 1)
BlackCard.create!(:text => "The CIA now interrogates enemy agents by repeatedly subjecting them to ________.", :blanks => 1)
BlackCard.create!(:text => "The class field trip was completely ruined by ________.", :blanks => 1)
BlackCard.create!(:text => "The Five Stages of Grief: denial, anger, bargaining, ________ acceptance.", :blanks => 1)
BlackCard.create!(:text => "The healing process began when I joined a support group for victims of ________.", :blanks => 1)
BlackCard.create!(:text => "The socialist governments of Scandanavia have declared that access to ________ is a basic human right.", :blanks => 1)
BlackCard.create!(:text => "The votes are in, and the new high school mascot is ________.", :blanks => 1)
BlackCard.create!(:text => "This holiday season, Tim Allen must overcome his fear of ________ to save Christmas.", :blanks => 1)
BlackCard.create!(:text => "This is the way the world ends This is the way the world ends Not with a bang but with ________.", :blanks => 1)
BlackCard.create!(:text => "This is your captain speaking. Fasten your seatbelts and prepare for ________.", :blanks => 1)
BlackCard.create!(:text => "This month's Cosmo: “Spice up your sex life by bringing ________ into the bedroom.”", :blanks => 1)
BlackCard.create!(:text => "This reason on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only ________ and his wits.", :blanks => 1)
BlackCard.create!(:text => "Tonight on 20/20: What you don't know about ________ could kill you.", :blanks => 1)
BlackCard.create!(:text => "TSA guidelines now prohibit ________ on airplanes.", :blanks => 1)
BlackCard.create!(:text => "Wake up, America. Christmas is under attack by secular liberals and their ________.", :blanks => 1)
BlackCard.create!(:text => "War! What is it good for? ________", :blanks => 1)
BlackCard.create!(:text => "What am I giving up for Lent? ________", :blanks => 1)
BlackCard.create!(:text => "What are my parents hiding from me? ________", :blanks => 1)
BlackCard.create!(:text => "What brought the orgy to a grinding halt? ________", :blanks => 1)
BlackCard.create!(:text => "What did I bring back from Mexico? ________", :blanks => 1)
BlackCard.create!(:text => "What did the US airdrop to the children of Afghanistan? ________", :blanks => 1)
BlackCard.create!(:text => "What did Vin Diesel eat for dinner? ________", :blanks => 1)
BlackCard.create!(:text => "What do old people smell like? ________", :blanks => 1)
BlackCard.create!(:text => "What does Dick Cheney prefer? ________", :blanks => 1)
BlackCard.create!(:text => "What don't you want to find in your Chinese food? ________", :blanks => 1)
BlackCard.create!(:text => "What ended my last relationship? ________", :blanks => 1)
BlackCard.create!(:text => "What gets better with age? ________", :blanks => 1)
BlackCard.create!(:text => "What gives me uncontrollable gas? ________", :blanks => 1)
BlackCard.create!(:text => "What has been making life difficult at the nudist colony? ________", :blanks => 1)
BlackCard.create!(:text => "What helps Obama unwind? ________", :blanks => 1)
BlackCard.create!(:text => "What is Batman's guilty pleasure? ________", :blanks => 1)
BlackCard.create!(:text => "What keeps me warm during the cold, cold winter? ________", :blanks => 1)
BlackCard.create!(:text => "What never fails to liven up the party? ________", :blanks => 1)
BlackCard.create!(:text => "What people like ________.", :blanks => 1)
BlackCard.create!(:text => "What will always get you laid? ________", :blanks => 1)
BlackCard.create!(:text => "What will I bring back in time to convince people that I am a powerful wizard? ________", :blanks => 1)
BlackCard.create!(:text => "What would grandma find disturbing, yet oddly charming? ________", :blanks => 1)
BlackCard.create!(:text => "What's a girl's best friend? ________", :blanks => 1)
BlackCard.create!(:text => "What's my anti-drug? ________", :blanks => 1)
BlackCard.create!(:text => "What's my secret power? ________", :blanks => 1)
BlackCard.create!(:text => "What's Teach for America using to inspire inner city students to succeed? ________", :blanks => 1)
BlackCard.create!(:text => "What's that smell? ________", :blanks => 1)
BlackCard.create!(:text => "What's that sound? ________", :blanks => 1)
BlackCard.create!(:text => "What's the crustiest? ________", :blanks => 1)
BlackCard.create!(:text => "What's the gift that keeps on giving? ________", :blanks => 1)
BlackCard.create!(:text => "What's the most emo? ________", :blanks => 1)
BlackCard.create!(:text => "What's the new fad diet? ________", :blanks => 1)
BlackCard.create!(:text => "What's the next Happy Meal toy? ________", :blanks => 1)
BlackCard.create!(:text => "What's there a ton of in heaven? ________", :blanks => 1)
BlackCard.create!(:text => "When all else fails, I can always masturbate to ________.", :blanks => 1)
BlackCard.create!(:text => "When I am a billionaire, I shall erect a 50-foot statue to commemorate ________.", :blanks => 1)
BlackCard.create!(:text => "When I am President of the United States, I will create the Department of ________.", :blanks => 1)
BlackCard.create!(:text => "When I pooped, what came out of my butt? ________", :blanks => 1)
BlackCard.create!(:text => "When Pharaoh remained unmoved, Moses called down a Plague of ________.", :blanks => 1)
BlackCard.create!(:text => "When the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ________.", :blanks => 1)
BlackCard.create!(:text => "Why am I sticky? ________", :blanks => 1)
BlackCard.create!(:text => "Why can't I sleep at night? ________", :blanks => 1)
BlackCard.create!(:text => "Why do I hurt all over? ________", :blanks => 1)

p = Playa.create!(:email => 'blank@example.com')

# p = Playa.first
b_length = BlackCard.count
w_length = WhiteCard.count
3000.times do |i|
  e = Entry.new
  e.playa_id = p.id
  e.black_card_id = rand(b_length) + 1
  BlackCard.find(e.black_card_id).blanks.times do
      e.white_cards << WhiteCard.find(rand(w_length) + 1)
  end
  e.save!
end
