# encoding: UTF-8

# WhiteCard.create!(:text => "")

BlackCard.create!(:text => "________, kid-tested mother-approved.", :blanks => 1)
BlackCard.create!(:text => "________: good to the last drop.", :blanks => 1)
BlackCard.create!(:text => "________? There's an app for that.", :blanks => 1)
BlackCard.create!(:text => "________. Betcha can't have just one.", :blanks => 1)
BlackCard.create!(:text => "________. High five bro.", :blanks => 1)
BlackCard.create!(:text => "________. It's a trap!", :blanks => 1)
BlackCard.create!(:text => "________. That's how I want to die.", :blanks => 1)
BlackCard.create!(:text => "________ + ________ = ________", :blanks => 3)
BlackCard.create!(:text => "I went from ________ to ________, all thanks to ________.", :blanks => 3)
BlackCard.create!(:text => "Make a haiku. ________ ________ ________", :blanks => 3)
BlackCard.create!(:text => "________ would be woefully incomplete without ________.", :blanks => 2)
BlackCard.create!(:text => "________ is a slippery slope that leads to ________.", :blanks => 2)
BlackCard.create!(:text => "An international tribunal has found ________ guilty of ________.", :blanks => 2)
BlackCard.create!(:text => "And the Academy Award for ________ goes to ________.", :blanks => 2)
BlackCard.create!(:text => "Before ________, all we had was ________.", :blanks => 2)
BlackCard.create!(:text => "Dear Sir or Madam, We regret to inform you that the office of ________ has denied your request for ________.", :blanks => 2)
BlackCard.create!(:text => "For my next trick, I will pull ________ out of ________.", :blanks => 2)
BlackCard.create!(:text => "I never truly understood ________ until I encountered ________.", :blanks => 2)
BlackCard.create!(:text => "I spent my whole life working toward ________, only to have it ruined by ________.", :blanks => 2)
BlackCard.create!(:text => "If God didn't want us to enjoy ________, he wouldn't have given us ________.", :blanks => 2)
BlackCard.create!(:text => "In a pinch, ________ can be a suitable substitute for ________.", :blanks => 2)
BlackCard.create!(:text => "In a world ravaged by ________, our only solace is ________.", :blanks => 2)
BlackCard.create!(:text => "In M. Night Shamalan's new movie, Bruce Willis discovers that ________ had really been ________ all along.", :blanks => 2)
BlackCard.create!(:text => "Lifetime presents ________, the story of ________.", :blanks => 2)
BlackCard.create!(:text => "Michael Bay's new three-hour action epic pits ________ against ________.", :blanks => 2)
BlackCard.create!(:text => "Rumor has it that Vladimir Putin's favorite dish is ________ stuffed with ________.", :blanks => 2)
BlackCard.create!(:text => "Step 1: ________ Step 2 ________ Step 3: Profit.", :blanks => 2)
BlackCard.create!(:text => "That's right I killed ________. How you ask? ________.", :blanks => 2)
BlackCard.create!(:text => "What's the next superhero/sidekick duo? ________ and ________", :blanks => 2)
BlackCard.create!(:text => "When I was tripping on acid ________ turned into ________.", :blanks => 2)
BlackCard.create!(:text => "You haven't truly lived until you've experienced ________ and ________ at the same time.", :blanks => 2)
BlackCard.create!(:text => "A romantic candlelit dinner would be incomplete without ________.", :blanks => 1)
BlackCard.create!(:text => "After blacking out during New Year's Eve, I was awoken by ________.", :blanks => 1)
BlackCard.create!(:text => "After months of debate, the Occupy Wall Street General Assembly could only agree on “More ________!”", :blanks => 1)
BlackCard.create!(:text => "After the earthquake, Sean Penn brought ________ to the people of Haiti.", :blanks => 1)
BlackCard.create!(:text => "Alternative medicine is now embracing the curative powers of ________.", :blanks => 1)
BlackCard.create!(:text => "And I would have gotten away with it, too, if it hadn't been for ________.", :blanks => 1)
BlackCard.create!(:text => "Anthropologists have recently discovered a primitive tribe that worships ________.", :blanks => 1)
BlackCard.create!(:text => "Before I run for president, I must destroy all evidence of my involvement with ________.", :blanks => 1)
BlackCard.create!(:text => "BILLY MAYS HERE FOR ________.", :blanks => 1)
BlackCard.create!(:text => "But before I kill you, Mr. Bond, I must show you ________.", :blanks => 1)
BlackCard.create!(:text => "Charades was ruined for me forever when my mom had to act out ________.", :blanks => 1)
BlackCard.create!(:text => "Coming to Broadway this season, ________: The Musical.", :blanks => 1)
BlackCard.create!(:text => "Dear Abby, I'm having some trouble with ________ and would like your advice.", :blanks => 1)
BlackCard.create!(:text => "During his midlife crisis, my dad got really into ________.", :blanks => 1)
BlackCard.create!(:text => "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of ________.", :blanks => 1)
BlackCard.create!(:text => "During sex, I like to think about ________.", :blanks => 1)
BlackCard.create!(:text => "Every Christmas my uncle gets drunk and tells the story about ________.", :blanks => 1)
BlackCard.create!(:text => "Everyone down on the ground! We don't want to hurt anyone. We're just here for ________.", :blanks => 1)
BlackCard.create!(:text => "He who controls ________ controls the world.", :blanks => 1)
BlackCard.create!(:text => "How am I maintaining my relationship status? ________", :blanks => 1)
BlackCard.create!(:text => "I do not know with what weapons World War III will be fought, but World War IV will be fought with ________.", :blanks => 1)
BlackCard.create!(:text => "I drink to forget ________.", :blanks => 1)
BlackCard.create!(:text => "I got 99 problems but ________ ain't one.", :blanks => 1)
BlackCard.create!(:text => "I learned the hard way that you can't cheer up a grieving friend with ________.", :blanks => 1)
BlackCard.create!(:text => "I'm sorry professor, but I couldn't complete my homework because of ________.", :blanks => 1)
BlackCard.create!(:text => "In 1,000 years when paper money is but a distant memory, ________ will be our currency.", :blanks => 1)
BlackCard.create!(:text => "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on ________.", :blanks => 1)
BlackCard.create!(:text => "In his new self-produced album, Kanye West raps over the sounds of ________.", :blanks => 1)
BlackCard.create!(:text => "In his newest and most difficult stunt, David Blaine must escape from ________.", :blanks => 1)
BlackCard.create!(:text => "In its new tourism campaign, Detroit proclaims that it has finally eliminated ________.", :blanks => 1)
BlackCard.create!(:text => "In L.A. county Jail, word is you can trade 200 cigarettes for ________.", :blanks => 1)
BlackCard.create!(:text => "In Michael Jackson's final moments, he thought about ________.", :blanks => 1)
BlackCard.create!(:text => "In Rome, there are whisperings that the Vatican has a secret room devoted to ________.", :blanks => 1)
BlackCard.create!(:text => "In the distant future, historians will agree that ________ marked the beginning of America's decline.", :blanks => 1)
BlackCard.create!(:text => "In the new Disney Channel Original Movie, Hannah Montana struggles with ________ for the first time.", :blanks => 1)
BlackCard.create!(:text => "Instead of coal, Santa now gives the bad children ________ .", :blanks => 1)
BlackCard.create!(:text => "It's a pity that kids these days are all getting involved with ________.", :blanks => 1)
BlackCard.create!(:text => "Jesus is ________.", :blanks => 1)
BlackCard.create!(:text => "Life for American Indians was forever changed when the White Man introduced them to ________.", :blanks => 1)
BlackCard.create!(:text => "Little Miss Muffet, Sat on a tuffet, Eating her curds and ________.", :blanks => 1)
BlackCard.create!(:text => "Major League Baseball has banned ________ for giving players an unfair advantage.", :blanks => 1)
BlackCard.create!(:text => "Maybe she's born with it. Maybe it's ________.", :blanks => 1)
BlackCard.create!(:text => "Members of New York's social elite are paying thousands of dollars just to experience ________.", :blanks => 1)
BlackCard.create!(:text => "MTV's new reality show features eight washed-up celebrities living with ________.", :blanks => 1)
BlackCard.create!(:text => "My country, 'tis of thee, sweet land of ________.", :blanks => 1)
BlackCard.create!(:text => "My mom freaked out when she looked at my browser history and found ________.com/________.", :blanks => 2)
BlackCard.create!(:text => "My new favorite porn star is Joey “________” McGee.", :blanks => 1)
BlackCard.create!(:text => "Next from J.K. Rowling: Harry Potter and the Chamber of ________.", :blanks => 1)
BlackCard.create!(:text => "Next on ESPN2: The World Series of ________.", :blanks => 1)
BlackCard.create!(:text => "Next time on Dr. Phil: How to talk to your child about ________.", :blanks => 1)
BlackCard.create!(:text => "On the third day of Christmas, my true love game to me: three French hens, two turtle doves, and ________.", :blanks => 1)
BlackCard.create!(:text => "Only two things in life are certain: death and ________.", :blanks => 1)
BlackCard.create!(:text => "Science will never explain the origin of ________.", :blanks => 1)
BlackCard.create!(:text => "Studies show that lab rats navigate mazes 50% faster after being exposed to ________", :blanks => 1)
BlackCard.create!(:text => "The CIA now interrogates enemy agents by repeatedly subjecting them to ________.", :blanks => 1)
BlackCard.create!(:text => "The class field trip was completely ruined by ________.", :blanks => 1)
BlackCard.create!(:text => "The Five Stages of Grief: denial, anger, bargaining, ________ acceptance.", :blanks => 1)
BlackCard.create!(:text => "The healing process began when I joined a support group for victims of ________.", :blanks => 1)
BlackCard.create!(:text => "The socialist governments of Scandanavia have declared that access to ________ is a basic human right.", :blanks => 1)
BlackCard.create!(:text => "The votes are in, and the new high school mascot is ________.", :blanks => 1)
BlackCard.create!(:text => "This holiday season, Tim Allen must overcome his fear of ________ to save Christmas.", :blanks => 1)
BlackCard.create!(:text => "This is the way the world ends This is the way the world ends Not with a bang but with ________.", :blanks => 1)
BlackCard.create!(:text => "This is your captain speaking. Fasten your seatbelts and prepare for ________.", :blanks => 1)
BlackCard.create!(:text => "This month's Cosmo: “Spice up your sex life by bringing ________ into the bedroom.”", :blanks => 1)
BlackCard.create!(:text => "This reason on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only ________ and his wits.", :blanks => 1)
BlackCard.create!(:text => "Tonight on 20/20: What you don't know about ________ could kill you.", :blanks => 1)
BlackCard.create!(:text => "TSA guidelines now prohibit ________ on airplanes.", :blanks => 1)
BlackCard.create!(:text => "Wake up, America. Christmas is under attack by secular liberals and their ________.", :blanks => 1)
BlackCard.create!(:text => "War! What is it good for? ________", :blanks => 1)
BlackCard.create!(:text => "What am I giving up for Lent? ________", :blanks => 1)
BlackCard.create!(:text => "What are my parents hiding from me? ________", :blanks => 1)
BlackCard.create!(:text => "What brought the orgy to a grinding halt? ________", :blanks => 1)
BlackCard.create!(:text => "What did I bring back from Mexico? ________", :blanks => 1)
BlackCard.create!(:text => "What did the US airdrop to the children of Afghanistan? ________", :blanks => 1)
BlackCard.create!(:text => "What did Vin Diesel eat for dinner? ________", :blanks => 1)
BlackCard.create!(:text => "What do old people smell like? ________", :blanks => 1)
BlackCard.create!(:text => "What does Dick Cheney prefer? ________", :blanks => 1)
BlackCard.create!(:text => "What don't you want to find in your Chinese food? ________", :blanks => 1)
BlackCard.create!(:text => "What ended my last relationship? ________", :blanks => 1)
BlackCard.create!(:text => "What gets better with age? ________", :blanks => 1)
BlackCard.create!(:text => "What gives me uncontrollable gas? ________", :blanks => 1)
BlackCard.create!(:text => "What has been making life difficult at the nudist colony? ________", :blanks => 1)
BlackCard.create!(:text => "What helps Obama unwind? ________", :blanks => 1)
BlackCard.create!(:text => "What is Batman's guilty pleasure? ________", :blanks => 1)
BlackCard.create!(:text => "What keeps me warm during the cold, cold winter? ________", :blanks => 1)
BlackCard.create!(:text => "What never fails to liven up the party? ________", :blanks => 1)
BlackCard.create!(:text => "What people like ________.", :blanks => 1)
BlackCard.create!(:text => "What will always get you laid? ________", :blanks => 1)
BlackCard.create!(:text => "What will I bring back in time to convince people that I am a powerful wizard? ________", :blanks => 1)
BlackCard.create!(:text => "What would grandma find disturbing, yet oddly charming? ________", :blanks => 1)
BlackCard.create!(:text => "What's a girl's best friend? ________", :blanks => 1)
BlackCard.create!(:text => "What's my anti-drug? ________", :blanks => 1)
BlackCard.create!(:text => "What's my secret power? ________", :blanks => 1)
BlackCard.create!(:text => "What's Teach for America using to inspire inner city students to succeed? ________", :blanks => 1)
BlackCard.create!(:text => "What's that smell? ________", :blanks => 1)
BlackCard.create!(:text => "What's that sound? ________", :blanks => 1)
BlackCard.create!(:text => "What's the crustiest? ________", :blanks => 1)
BlackCard.create!(:text => "What's the gift that keeps on giving? ________", :blanks => 1)
BlackCard.create!(:text => "What's the most emo? ________", :blanks => 1)
BlackCard.create!(:text => "What's the new fad diet? ________", :blanks => 1)
BlackCard.create!(:text => "What's the next Happy Meal toy? ________", :blanks => 1)
BlackCard.create!(:text => "What's there a ton of in heaven? ________", :blanks => 1)
BlackCard.create!(:text => "When all else fails, I can always masturbate to ________.", :blanks => 1)
BlackCard.create!(:text => "When I am a billionaire, I shall erect a 50-foot statue to commemorate ________.", :blanks => 1)
BlackCard.create!(:text => "When I am President of the United States, I will create the Department of ________.", :blanks => 1)
BlackCard.create!(:text => "When I pooped, what came out of my butt? ________", :blanks => 1)
BlackCard.create!(:text => "When Pharaoh remained unmoved, Moses called down a Plague of ________.", :blanks => 1)
BlackCard.create!(:text => "When the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ________.", :blanks => 1)
BlackCard.create!(:text => "Why am I sticky? ________", :blanks => 1)
BlackCard.create!(:text => "Why can't I sleep at night? ________", :blanks => 1)
BlackCard.create!(:text => "Why do I hurt all over? ________", :blanks => 1)

p = Playa.create!()

b_length = BlackCard.count
w_length = WhiteCard.count
12.times do |i|
  e = Entry.new
  e.playa_id = p.id
  e.black_card_id = rand(b_length) + 1
  BlackCard.find(e.black_card_id).blanks.times do
      e.white_cards << WhiteCard.find(rand(w_length) + 1)
  end
  e.save!
end
