require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlayasController do

  # This should return the minimal set of attributes required to create a valid
  # Playa. As you add validations to Playa, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "email" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlayasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all playas as @playas" do
      playa = Playa.create! valid_attributes
      get :index, {}, valid_session
      assigns(:playas).should eq([playa])
    end
  end

  describe "GET show" do
    it "assigns the requested playa as @playa" do
      playa = Playa.create! valid_attributes
      get :show, {:id => playa.to_param}, valid_session
      assigns(:playa).should eq(playa)
    end
  end

  describe "GET new" do
    it "assigns a new playa as @playa" do
      get :new, {}, valid_session
      assigns(:playa).should be_a_new(Playa)
    end
  end

  describe "GET edit" do
    it "assigns the requested playa as @playa" do
      playa = Playa.create! valid_attributes
      get :edit, {:id => playa.to_param}, valid_session
      assigns(:playa).should eq(playa)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Playa" do
        expect {
          post :create, {:playa => valid_attributes}, valid_session
        }.to change(Playa, :count).by(1)
      end

      it "assigns a newly created playa as @playa" do
        post :create, {:playa => valid_attributes}, valid_session
        assigns(:playa).should be_a(Playa)
        assigns(:playa).should be_persisted
      end

      it "redirects to the created playa" do
        post :create, {:playa => valid_attributes}, valid_session
        response.should redirect_to(Playa.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved playa as @playa" do
        # Trigger the behavior that occurs when invalid params are submitted
        Playa.any_instance.stub(:save).and_return(false)
        post :create, {:playa => { "email" => "invalid value" }}, valid_session
        assigns(:playa).should be_a_new(Playa)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Playa.any_instance.stub(:save).and_return(false)
        post :create, {:playa => { "email" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested playa" do
        playa = Playa.create! valid_attributes
        # Assuming there are no other playas in the database, this
        # specifies that the Playa created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Playa.any_instance.should_receive(:update_attributes).with({ "email" => "MyString" })
        put :update, {:id => playa.to_param, :playa => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested playa as @playa" do
        playa = Playa.create! valid_attributes
        put :update, {:id => playa.to_param, :playa => valid_attributes}, valid_session
        assigns(:playa).should eq(playa)
      end

      it "redirects to the playa" do
        playa = Playa.create! valid_attributes
        put :update, {:id => playa.to_param, :playa => valid_attributes}, valid_session
        response.should redirect_to(playa)
      end
    end

    describe "with invalid params" do
      it "assigns the playa as @playa" do
        playa = Playa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Playa.any_instance.stub(:save).and_return(false)
        put :update, {:id => playa.to_param, :playa => { "email" => "invalid value" }}, valid_session
        assigns(:playa).should eq(playa)
      end

      it "re-renders the 'edit' template" do
        playa = Playa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Playa.any_instance.stub(:save).and_return(false)
        put :update, {:id => playa.to_param, :playa => { "email" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested playa" do
      playa = Playa.create! valid_attributes
      expect {
        delete :destroy, {:id => playa.to_param}, valid_session
      }.to change(Playa, :count).by(-1)
    end

    it "redirects to the playas list" do
      playa = Playa.create! valid_attributes
      delete :destroy, {:id => playa.to_param}, valid_session
      response.should redirect_to(playas_url)
    end
  end

end
